name: Build and Zip Site

on:
  push:
    branches:
      - main 

jobs:
  build_and_zip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install
        
    - name: Build Site
      run: bundle exec jekyll build
      
    - name: Compress Site
      run: |
        mkdir -p _static
        zip -r _static/arrrrmada.zip _site
    
    - name: Commit and Push Zip File
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _static/arrrrmada.zip
        git commit -m "Update _static/arrrrmada.zip" || echo "No changes to commit"
        git push origin main  # or the branch you are using
